service: aws-python-rest-api

frameworkVersion: '3'


provider:
  name: aws
  runtime: python3.9

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get
  getStats:
    handler: dailyCycle.getStats
    events:
      - http:
          path: /
          method: get


plugins:
  - serverless-python-requirements
